/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as EquipementsRouteImport } from './routes/equipements'
import { Route as EntretienRouteImport } from './routes/entretien'
import { Route as DepannageRouteImport } from './routes/depannage'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConstructionRouteImport } from './routes/construction'
import { Route as AutomatisationRouteImport } from './routes/automatisation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZonesYverdonLesBainsRouteImport } from './routes/zones.yverdon-les-bains'
import { Route as ZonesPayerneRouteImport } from './routes/zones.payerne'
import { Route as ZonesNeuchatelRouteImport } from './routes/zones.neuchatel'
import { Route as ZonesMoratRouteImport } from './routes/zones.morat'
import { Route as ZonesLucensRouteImport } from './routes/zones.lucens'
import { Route as ZonesFribourgRouteImport } from './routes/zones.fribourg'
import { Route as ZonesEstavayerLeLacRouteImport } from './routes/zones.estavayer-le-lac'
import { Route as ZonesAvenchesRouteImport } from './routes/zones.avenches'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipementsRoute = EquipementsRouteImport.update({
  id: '/equipements',
  path: '/equipements',
  getParentRoute: () => rootRouteImport,
} as any)
const EntretienRoute = EntretienRouteImport.update({
  id: '/entretien',
  path: '/entretien',
  getParentRoute: () => rootRouteImport,
} as any)
const DepannageRoute = DepannageRouteImport.update({
  id: '/depannage',
  path: '/depannage',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionRoute = ConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomatisationRoute = AutomatisationRouteImport.update({
  id: '/automatisation',
  path: '/automatisation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesYverdonLesBainsRoute = ZonesYverdonLesBainsRouteImport.update({
  id: '/zones/yverdon-les-bains',
  path: '/zones/yverdon-les-bains',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesPayerneRoute = ZonesPayerneRouteImport.update({
  id: '/zones/payerne',
  path: '/zones/payerne',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesNeuchatelRoute = ZonesNeuchatelRouteImport.update({
  id: '/zones/neuchatel',
  path: '/zones/neuchatel',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesMoratRoute = ZonesMoratRouteImport.update({
  id: '/zones/morat',
  path: '/zones/morat',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesLucensRoute = ZonesLucensRouteImport.update({
  id: '/zones/lucens',
  path: '/zones/lucens',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesFribourgRoute = ZonesFribourgRouteImport.update({
  id: '/zones/fribourg',
  path: '/zones/fribourg',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesEstavayerLeLacRoute = ZonesEstavayerLeLacRouteImport.update({
  id: '/zones/estavayer-le-lac',
  path: '/zones/estavayer-le-lac',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesAvenchesRoute = ZonesAvenchesRouteImport.update({
  id: '/zones/avenches',
  path: '/zones/avenches',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automatisation': typeof AutomatisationRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/depannage': typeof DepannageRoute
  '/entretien': typeof EntretienRoute
  '/equipements': typeof EquipementsRoute
  '/produits': typeof ProduitsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zones/avenches': typeof ZonesAvenchesRoute
  '/zones/estavayer-le-lac': typeof ZonesEstavayerLeLacRoute
  '/zones/fribourg': typeof ZonesFribourgRoute
  '/zones/lucens': typeof ZonesLucensRoute
  '/zones/morat': typeof ZonesMoratRoute
  '/zones/neuchatel': typeof ZonesNeuchatelRoute
  '/zones/payerne': typeof ZonesPayerneRoute
  '/zones/yverdon-les-bains': typeof ZonesYverdonLesBainsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automatisation': typeof AutomatisationRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/depannage': typeof DepannageRoute
  '/entretien': typeof EntretienRoute
  '/equipements': typeof EquipementsRoute
  '/produits': typeof ProduitsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zones/avenches': typeof ZonesAvenchesRoute
  '/zones/estavayer-le-lac': typeof ZonesEstavayerLeLacRoute
  '/zones/fribourg': typeof ZonesFribourgRoute
  '/zones/lucens': typeof ZonesLucensRoute
  '/zones/morat': typeof ZonesMoratRoute
  '/zones/neuchatel': typeof ZonesNeuchatelRoute
  '/zones/payerne': typeof ZonesPayerneRoute
  '/zones/yverdon-les-bains': typeof ZonesYverdonLesBainsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automatisation': typeof AutomatisationRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/depannage': typeof DepannageRoute
  '/entretien': typeof EntretienRoute
  '/equipements': typeof EquipementsRoute
  '/produits': typeof ProduitsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zones/avenches': typeof ZonesAvenchesRoute
  '/zones/estavayer-le-lac': typeof ZonesEstavayerLeLacRoute
  '/zones/fribourg': typeof ZonesFribourgRoute
  '/zones/lucens': typeof ZonesLucensRoute
  '/zones/morat': typeof ZonesMoratRoute
  '/zones/neuchatel': typeof ZonesNeuchatelRoute
  '/zones/payerne': typeof ZonesPayerneRoute
  '/zones/yverdon-les-bains': typeof ZonesYverdonLesBainsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automatisation'
    | '/construction'
    | '/contact'
    | '/depannage'
    | '/entretien'
    | '/equipements'
    | '/produits'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/zones/avenches'
    | '/zones/estavayer-le-lac'
    | '/zones/fribourg'
    | '/zones/lucens'
    | '/zones/morat'
    | '/zones/neuchatel'
    | '/zones/payerne'
    | '/zones/yverdon-les-bains'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automatisation'
    | '/construction'
    | '/contact'
    | '/depannage'
    | '/entretien'
    | '/equipements'
    | '/produits'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/zones/avenches'
    | '/zones/estavayer-le-lac'
    | '/zones/fribourg'
    | '/zones/lucens'
    | '/zones/morat'
    | '/zones/neuchatel'
    | '/zones/payerne'
    | '/zones/yverdon-les-bains'
  id:
    | '__root__'
    | '/'
    | '/automatisation'
    | '/construction'
    | '/contact'
    | '/depannage'
    | '/entretien'
    | '/equipements'
    | '/produits'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/zones/avenches'
    | '/zones/estavayer-le-lac'
    | '/zones/fribourg'
    | '/zones/lucens'
    | '/zones/morat'
    | '/zones/neuchatel'
    | '/zones/payerne'
    | '/zones/yverdon-les-bains'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomatisationRoute: typeof AutomatisationRoute
  ConstructionRoute: typeof ConstructionRoute
  ContactRoute: typeof ContactRoute
  DepannageRoute: typeof DepannageRoute
  EntretienRoute: typeof EntretienRoute
  EquipementsRoute: typeof EquipementsRoute
  ProduitsRoute: typeof ProduitsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ZonesAvenchesRoute: typeof ZonesAvenchesRoute
  ZonesEstavayerLeLacRoute: typeof ZonesEstavayerLeLacRoute
  ZonesFribourgRoute: typeof ZonesFribourgRoute
  ZonesLucensRoute: typeof ZonesLucensRoute
  ZonesMoratRoute: typeof ZonesMoratRoute
  ZonesNeuchatelRoute: typeof ZonesNeuchatelRoute
  ZonesPayerneRoute: typeof ZonesPayerneRoute
  ZonesYverdonLesBainsRoute: typeof ZonesYverdonLesBainsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipements': {
      id: '/equipements'
      path: '/equipements'
      fullPath: '/equipements'
      preLoaderRoute: typeof EquipementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entretien': {
      id: '/entretien'
      path: '/entretien'
      fullPath: '/entretien'
      preLoaderRoute: typeof EntretienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depannage': {
      id: '/depannage'
      path: '/depannage'
      fullPath: '/depannage'
      preLoaderRoute: typeof DepannageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automatisation': {
      id: '/automatisation'
      path: '/automatisation'
      fullPath: '/automatisation'
      preLoaderRoute: typeof AutomatisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/yverdon-les-bains': {
      id: '/zones/yverdon-les-bains'
      path: '/zones/yverdon-les-bains'
      fullPath: '/zones/yverdon-les-bains'
      preLoaderRoute: typeof ZonesYverdonLesBainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/payerne': {
      id: '/zones/payerne'
      path: '/zones/payerne'
      fullPath: '/zones/payerne'
      preLoaderRoute: typeof ZonesPayerneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/neuchatel': {
      id: '/zones/neuchatel'
      path: '/zones/neuchatel'
      fullPath: '/zones/neuchatel'
      preLoaderRoute: typeof ZonesNeuchatelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/morat': {
      id: '/zones/morat'
      path: '/zones/morat'
      fullPath: '/zones/morat'
      preLoaderRoute: typeof ZonesMoratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/lucens': {
      id: '/zones/lucens'
      path: '/zones/lucens'
      fullPath: '/zones/lucens'
      preLoaderRoute: typeof ZonesLucensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/fribourg': {
      id: '/zones/fribourg'
      path: '/zones/fribourg'
      fullPath: '/zones/fribourg'
      preLoaderRoute: typeof ZonesFribourgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/estavayer-le-lac': {
      id: '/zones/estavayer-le-lac'
      path: '/zones/estavayer-le-lac'
      fullPath: '/zones/estavayer-le-lac'
      preLoaderRoute: typeof ZonesEstavayerLeLacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/avenches': {
      id: '/zones/avenches'
      path: '/zones/avenches'
      fullPath: '/zones/avenches'
      preLoaderRoute: typeof ZonesAvenchesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomatisationRoute: AutomatisationRoute,
  ConstructionRoute: ConstructionRoute,
  ContactRoute: ContactRoute,
  DepannageRoute: DepannageRoute,
  EntretienRoute: EntretienRoute,
  EquipementsRoute: EquipementsRoute,
  ProduitsRoute: ProduitsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ZonesAvenchesRoute: ZonesAvenchesRoute,
  ZonesEstavayerLeLacRoute: ZonesEstavayerLeLacRoute,
  ZonesFribourgRoute: ZonesFribourgRoute,
  ZonesLucensRoute: ZonesLucensRoute,
  ZonesMoratRoute: ZonesMoratRoute,
  ZonesNeuchatelRoute: ZonesNeuchatelRoute,
  ZonesPayerneRoute: ZonesPayerneRoute,
  ZonesYverdonLesBainsRoute: ZonesYverdonLesBainsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
